import { Country, FullCountry } from '../types/countries.model';

export const makeCountry = (overrides: Partial<Country> = {}): Country => ({
  name: { common: 'Germany', official: 'Federal Republic of Germany', nativeName: {} },
  flags: { png: 'de.png', svg: 'de.svg', alt: 'Flag of Germany' },
  cca3: 'DEU',
  currencies: { EUR: { name: 'Euro', symbol: '€' } },
  languages: { deu: 'German' },
  capital: ['Berlin'],
  region: 'Europe',
  borders: ['FRA', 'AUT'],
  area: 357114,
  population: 83000000,
  ...overrides,
});

export const makeFullCountry = (overrides: Partial<FullCountry> = {}): FullCountry => ({
  ...makeCountry(),
  tld: ['.de'],
  cca2: 'DE',
  ccn3: '276',
  cioc: 'GER',
  independent: true,
  status: 'officially-assigned',
  unMember: true,
  idd: { root: '+4', suffixes: ['9'] },
  altSpellings: ['DE'],
  timezones: ['UTC+01:00', 'UTC+02:00'],
  subregion: 'Western Europe',
  landlocked: false,
  maps: { googleMaps: '', openStreetMaps: '' },
  fifa: 'GER',
  car: { signs: ['DY'], side: 'right' },
  continents: ['Europe'],
  flag: '🇩🇪',
  latlng: [51, 9],
  demonyms: {},
  translations: {},
  coatOfArms: { png: '', svg: '' },
  startOfWeek: 'monday',
  capitalInfo: { latlng: [52.52, 13.4] },
  postalCode: { format: '#####', regex: null },
  ...overrides,
});
